using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker_EN.Camera;

/// <summary>
/// Minimal borderless window for displaying a captured photograph.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STPhotoWindow : BaseWindow
{
    public STPhotoWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        CloseButton.OnPressed += _ => Close();
    }

    /// <summary>
    /// Display the photo texture and hide the loading label.
    /// </summary>
    public void SetTexture(Texture texture)
    {
        PhotoTexture.Texture = texture;
        LoadingLabel.Visible = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }
}
