using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics;
using Robust.Shared.Maths;
using Robust.Client.GameObjects;
using Robust.Shared.Utility;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Shared.Log;
using Robust.Shared.IoC;

namespace Content.Client._Stalker.PdaMessenger;

[GenerateTypedNameReferences]
public sealed partial class PdaNotificationPanel : PanelContainer
{
    public PdaNotificationPanel(string title, string content, string sender, string? bandId = null)
    {
        RobustXamlLoader.Load(this);

        TitleLabel.Text = title;
        ContentLabel.SetMessage(FormattedMessage.FromMarkup(content));

        // Display faction icon if bandId is provided
        if (!string.IsNullOrEmpty(bandId))
        {
            try
            {
                var iconPath = new ResPath($"/Textures/_Stalker_EN/Factions/{bandId}.png");
                var resourceCache = IoCManager.Resolve<IResourceCache>();
                if (resourceCache.TryGetResource<TextureResource>(iconPath, out var texture))
                {
                    FactionIcon.Texture = texture;
                    FactionIcon.Visible = true;
                }
                else
                {
                    FactionIcon.Visible = false;
                }
            }
            catch
            {
                FactionIcon.Visible = false;
            }
        }
        else
        {
            FactionIcon.Visible = false;
        }

        // Panel style - transparent background
        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.Transparent,
        };
    }

    /// <summary>
    /// Sets the transparency of the notification content (text + icon), but not the background.
    /// Alpha: 1.0 = fully opaque, 0.0 = fully transparent
    /// </summary>
    public void SetAlpha(float alpha)
    {
        var clampedAlpha = MathHelper.Clamp(alpha, 0f, 1f);
        var modulate = Color.White.WithAlpha(clampedAlpha);

        // Apply to all children iteratively (avoids recursion)
        var stack = new Stack<Control>();
        stack.Push(this);

        while (stack.Count > 0)
        {
            var control = stack.Pop();
            control.ModulateSelfOverride = modulate;

            foreach (var child in control.Children)
            {
                if (child is Control childControl)
                    stack.Push(childControl);
            }
        }
    }
}
